        f90_simple needs f90_simple.o, midpoint.o and f.o.
          The commands to create f90_simple are
          f90 f90_simple.o midpoint.o sub2.o
          mv a.out f90_simple

        f90_simple.o needs f90_simple.f90.
          The command to create f90_simple.o is
          f90 -c f90_simple.f90

        midpoint.o needs midpoint.f90.
          The command to create midpoint.o is
          f90 -c midpoint.f90

        f.o needs f.f90.
          The command to create f.o is
          f90 -c f.f90
